// Code generated by oapi-codegen; DO NOT EDIT.

package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
)

// #/components/schemas/CheckExpand
type CheckExpand string

const (
	CheckExpandFeature      CheckExpand = "feature"
	CheckExpandPlan         CheckExpand = "plan"
	CheckExpandPlanFeatures CheckExpand = "plan.features"
)

// #/components/schemas/CheckResponse
type CheckResponse struct {
	// Whether the user has access to this feature
	Allowed bool `json:"allowed" form:"allowed"`
	// The checked feature (requires expand=feature)
	Feature *CheckResponseFeature `json:"feature,omitempty" form:"feature,omitempty"`
	// The user's current plan (requires expand=plan or expand=plan.features)
	Plan *CheckResponsePlan `json:"plan,omitempty" form:"plan,omitempty"`
	// Reason for the access decision
	Reason CheckResponseReason `json:"reason" form:"reason"`
	// The user ID
	UserID string `json:"user_id" form:"user_id"`
}

// #/components/schemas/CheckResponse/properties/feature
// The checked feature (requires expand=feature)
type CheckResponseFeature struct {
	Any0    *any
	Feature *Feature
}

func (u CheckResponseFeature) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if u.Any0 != nil {
		return json.Marshal(u.Any0)
	}
	if u.Feature != nil {
		data, err := json.Marshal(u.Feature)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (u *CheckResponseFeature) UnmarshalJSON(data []byte) error {
	var v0 any
	if err := json.Unmarshal(data, &v0); err == nil {
		u.Any0 = &v0
	}

	var v1 Feature
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Feature = &v1
	}

	return nil
}

// #/components/schemas/CheckResponse/properties/plan
// The user's current plan (requires expand=plan or expand=plan.features)
type CheckResponsePlan struct {
	Any0 *any
	Plan *Plan
}

func (u CheckResponsePlan) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if u.Any0 != nil {
		return json.Marshal(u.Any0)
	}
	if u.Plan != nil {
		data, err := json.Marshal(u.Plan)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (u *CheckResponsePlan) UnmarshalJSON(data []byte) error {
	var v0 any
	if err := json.Unmarshal(data, &v0); err == nil {
		u.Any0 = &v0
	}

	var v1 Plan
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Plan = &v1
	}

	return nil
}

// #/components/schemas/CheckResponse/properties/reason
// Reason for the access decision
type CheckResponseReason string

const (
	NoSubscription   CheckResponseReason = "no_subscription"
	DefaultPlan      CheckResponseReason = "default_plan"
	FeatureInPlan    CheckResponseReason = "feature_in_plan"
	InsufficientPlan CheckResponseReason = "insufficient_plan"
)

// #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error ProblemDetails `json:"error" form:"error"`
}

// #/components/schemas/Feature
type Feature struct {
	// Feature description
	Description *string `json:"description,omitempty" form:"description,omitempty"`
	// Feature identifier
	ID string `json:"id" form:"id"`
	// Feature display name
	Name string `json:"name" form:"name"`
}

// #/components/schemas/FeatureResponse
type FeatureResponse struct {
	Feature Feature `json:"feature" form:"feature"`
}

// #/components/schemas/FeaturesResponse
type FeaturesResponse struct {
	// All available features
	Features []Feature `json:"features" form:"features"`
}

// #/components/schemas/FeaturesResponse/properties/features
// All available features
type FeaturesResponseFeatures = []Feature

// #/components/schemas/FieldError
type FieldError struct {
	Field   string `json:"field" form:"field"`
	Message string `json:"message" form:"message"`
}

// #/components/schemas/LemonSqueezySubscription
type LemonSqueezySubscription struct {
	// Day of month for billing
	BillingAnchor int `json:"billing_anchor" form:"billing_anchor"`
	// Whether the subscription has been cancelled
	Cancelled bool `json:"cancelled" form:"cancelled"`
	// Payment card brand
	CardBrand string `json:"card_brand" form:"card_brand"`
	// Last four digits of payment card
	CardLastFour string `json:"card_last_four" form:"card_last_four"`
	// Unix timestamp when subscription was created
	CreatedAt int64 `json:"created_at" form:"created_at"`
	// LemonSqueezy customer ID
	CustomerID int `json:"customer_id" form:"customer_id"`
	// Unix timestamp when subscription ends
	EndsAt Nullable[int] `json:"ends_at,omitempty" form:"ends_at,omitempty"`
	// LemonSqueezy subscription ID
	ID int `json:"id" form:"id"`
	// LemonSqueezy order ID
	OrderID int `json:"order_id" form:"order_id"`
	// LemonSqueezy price ID
	PriceID int `json:"price_id" form:"price_id"`
	// LemonSqueezy product ID
	ProductID int `json:"product_id" form:"product_id"`
	// Product display name
	ProductName string `json:"product_name" form:"product_name"`
	// Number of intervals between billings
	RenewalIntervalQuantity int `json:"renewal_interval_quantity" form:"renewal_interval_quantity"`
	// Billing interval unit (month, year, etc.)
	RenewalIntervalUnit string `json:"renewal_interval_unit" form:"renewal_interval_unit"`
	// Unix timestamp when subscription renews
	RenewsAt int64 `json:"renews_at" form:"renews_at"`
	// Subscription status
	Status string `json:"status" form:"status"`
	// Human-readable subscription status
	StatusFormatted string `json:"status_formatted" form:"status_formatted"`
	// LemonSqueezy subscription item ID
	SubscriptionItemID int `json:"subscription_item_id" form:"subscription_item_id"`
	// Unix timestamp when trial ends
	TrialEndsAt Nullable[int] `json:"trial_ends_at,omitempty" form:"trial_ends_at,omitempty"`
	// Price in cents
	UnitPrice int `json:"unit_price" form:"unit_price"`
	// Unix timestamp when subscription was last updated
	UpdatedAt int64 `json:"updated_at" form:"updated_at"`
	// LemonSqueezy variant ID
	VariantID int `json:"variant_id" form:"variant_id"`
	// Variant display name
	VariantName string `json:"variant_name" form:"variant_name"`
}

// #/components/schemas/Meta
type Meta struct {
	RequestID string `json:"request_id" form:"request_id"`
	Timestamp string `json:"timestamp" form:"timestamp"`
	Version   string `json:"version" form:"version"`
}

// #/components/schemas/Plan
type Plan struct {
	// Plan description
	Description *string `json:"description,omitempty" form:"description,omitempty"`
	// Features included in this plan
	Features []Feature `json:"features,omitempty" form:"features,omitempty"`
	// Plan identifier
	ID string `json:"id" form:"id"`
	// Plan display name
	Name string `json:"name" form:"name"`
	// Pricing variants for this plan
	Variants []Variant `json:"variants,omitempty" form:"variants,omitempty"`
}

// #/components/schemas/Plan/properties/features
// Features included in this plan
type PlanFeatures = []Feature

// #/components/schemas/Plan/properties/variants
// Pricing variants for this plan
type PlanVariants = []Variant

// #/components/schemas/PlanExpand
type PlanExpand string

const (
	PlanExpandFeatures PlanExpand = "features"
)

// #/components/schemas/PlanResponse
type PlanResponse struct {
	Plan Plan `json:"plan" form:"plan"`
}

// #/components/schemas/PlansExpand
type PlansExpand string

const (
	PlansExpandFeatures PlansExpand = "features"
)

// #/components/schemas/PlansResponse
type PlansResponse struct {
	// List of available plans
	Plans []Plan `json:"plans" form:"plans"`
}

// #/components/schemas/PlansResponse/properties/plans
// List of available plans
type PlansResponsePlans = []Plan

// #/components/schemas/ProblemDetails
type ProblemDetails struct {
	Detail    string             `json:"detail" form:"detail"`
	Fields    []FieldError       `json:"fields,omitempty" form:"fields,omitempty"`
	RequestID string             `json:"request_id" form:"request_id"`
	Status    int                `json:"status" form:"status"`
	Title     string             `json:"title" form:"title"`
	Type      ProblemDetailsType `json:"type" form:"type"`
}

// #/components/schemas/ProblemDetails/properties/fields
type ProblemDetailsFields = []FieldError

// #/components/schemas/ProblemDetails/properties/type
type ProblemDetailsType string

const (
	HTTPSGrantsyExampleErrorsValidationFailed ProblemDetailsType = "https://grantsy.example/errors/validation-failed"
	HTTPSGrantsyExampleErrorsBadRequest       ProblemDetailsType = "https://grantsy.example/errors/bad-request"
	HTTPSGrantsyExampleErrorsNotFound         ProblemDetailsType = "https://grantsy.example/errors/not-found"
	HTTPSGrantsyExampleErrorsUnauthorized     ProblemDetailsType = "https://grantsy.example/errors/unauthorized"
	HTTPSGrantsyExampleErrorsInternalError    ProblemDetailsType = "https://grantsy.example/errors/internal-error"
)

// #/components/schemas/ProviderSubscription
type ProviderSubscription struct {
	LemonSqueezySubscription *LemonSqueezySubscription
}

func (u ProviderSubscription) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.LemonSqueezySubscription != nil {
		count++
		data, err = json.Marshal(u.LemonSqueezySubscription)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("ProviderSubscription: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *ProviderSubscription) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 LemonSqueezySubscription
	if err := json.Unmarshal(data, &v0); err == nil {
		u.LemonSqueezySubscription = &v0
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("ProviderSubscription: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// #/components/schemas/RawSubscription
type RawSubscription struct {
	Data ProviderSubscription `json:"data" form:"data"`
	// Provider identifier
	Provider RawSubscriptionProvider `json:"provider" form:"provider"`
}

// #/components/schemas/RawSubscription/properties/provider
// Provider identifier
type RawSubscriptionProvider string

const (
	Lemonsqueezy RawSubscriptionProvider = "lemonsqueezy"
)

// #/components/schemas/UserExpand
type UserExpand string

const (
	UserExpandPlan         UserExpand = "plan"
	UserExpandFeatures     UserExpand = "features"
	UserExpandSubscription UserExpand = "subscription"
)

// #/components/schemas/UserResponse
type UserResponse struct {
	// Features available to the user (requires expand=features)
	Features []Feature `json:"features,omitempty" form:"features,omitempty"`
	// Plan details (requires expand=plan)
	Plan *UserResponsePlan `json:"plan,omitempty" form:"plan,omitempty"`
	// The user's current plan ID
	PlanID string `json:"plan_id" form:"plan_id"`
	// Subscription details (requires expand=subscription)
	Subscription *UserResponseSubscription `json:"subscription,omitempty" form:"subscription,omitempty"`
	// The user ID
	UserID string `json:"user_id" form:"user_id"`
}

// #/components/schemas/UserResponse/properties/features
// Features available to the user (requires expand=features)
type UserResponseFeatures = []Feature

// #/components/schemas/UserResponse/properties/plan
// Plan details (requires expand=plan)
type UserResponsePlan struct {
	Any0 *any
	Plan *Plan
}

func (u UserResponsePlan) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if u.Any0 != nil {
		return json.Marshal(u.Any0)
	}
	if u.Plan != nil {
		data, err := json.Marshal(u.Plan)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (u *UserResponsePlan) UnmarshalJSON(data []byte) error {
	var v0 any
	if err := json.Unmarshal(data, &v0); err == nil {
		u.Any0 = &v0
	}

	var v1 Plan
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Plan = &v1
	}

	return nil
}

// #/components/schemas/UserResponse/properties/subscription
// Subscription details (requires expand=subscription)
type UserResponseSubscription struct {
	Any0             *any
	UserSubscription *UserSubscription
}

func (u UserResponseSubscription) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if u.Any0 != nil {
		return json.Marshal(u.Any0)
	}
	if u.UserSubscription != nil {
		data, err := json.Marshal(u.UserSubscription)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (u *UserResponseSubscription) UnmarshalJSON(data []byte) error {
	var v0 any
	if err := json.Unmarshal(data, &v0); err == nil {
		u.Any0 = &v0
	}

	var v1 UserSubscription
	if err := json.Unmarshal(data, &v1); err == nil {
		u.UserSubscription = &v1
	}

	return nil
}

// #/components/schemas/UserSubscription
type UserSubscription struct {
	// Whether the subscription has been cancelled
	Cancelled bool `json:"cancelled" form:"cancelled"`
	// Unix timestamp when subscription ends (if cancelled)
	EndsAt Nullable[int] `json:"ends_at,omitempty" form:"ends_at,omitempty"`
	// The plan ID this subscription is for
	PlanID string          `json:"plan_id" form:"plan_id"`
	Raw    RawSubscription `json:"raw" form:"raw"`
	// Unix timestamp when subscription renews
	RenewsAt Nullable[int] `json:"renews_at,omitempty" form:"renews_at,omitempty"`
	// Subscription status (active, on_trial, paused, past_due, cancelled, expired)
	Status string `json:"status" form:"status"`
	// Unix timestamp when trial ends (if on trial)
	TrialEndsAt Nullable[int] `json:"trial_ends_at,omitempty" form:"trial_ends_at,omitempty"`
}

// #/components/schemas/Variant
type Variant struct {
	// Whether this variant has a free trial
	HasFreeTrial bool `json:"has_free_trial" form:"has_free_trial"`
	// Variant identifier
	ID int `json:"id" form:"id"`
	// Billing interval (month, year, etc.)
	Interval string `json:"interval" form:"interval"`
	// Number of intervals between billings
	IntervalCount int `json:"interval_count" form:"interval_count"`
	// Variant display name
	Name string `json:"name" form:"name"`
	// Price in cents
	Price int `json:"price" form:"price"`
	// Display order
	Sort int `json:"sort" form:"sort"`
	// Trial billing interval
	TrialInterval *string `json:"trial_interval,omitempty" form:"trial_interval,omitempty"`
	// Trial duration in intervals
	TrialIntervalCount *int `json:"trial_interval_count,omitempty" form:"trial_interval_count,omitempty"`
}

// #/paths//v1/check/get/parameters/2/schema
// Fields to expand (use ?expand=feature&expand=plan&expand=plan.features)
type GetV1CheckParameter = []CheckExpand

// #/paths//v1/check/get/responses/200/content/application/json/schema
type GetV1Check200Response struct {
	Data *CheckResponse `json:"data,omitempty" form:"data,omitempty"`
	Meta *Meta          `json:"meta,omitempty" form:"meta,omitempty"`
}

// #/paths//v1/features/get/responses/200/content/application/json/schema
type GetV1Features200Response struct {
	Data *FeaturesResponse `json:"data,omitempty" form:"data,omitempty"`
	Meta *Meta             `json:"meta,omitempty" form:"meta,omitempty"`
}

// #/paths//v1/features/{feature_id}/get/responses/200/content/application/json/schema
type GetV1FeaturesFeatureID200Response struct {
	Data *FeatureResponse `json:"data,omitempty" form:"data,omitempty"`
	Meta *Meta            `json:"meta,omitempty" form:"meta,omitempty"`
}

// #/paths//v1/plans/get/parameters/0/schema
// Fields to expand (use ?expand=features)
type GetV1PlansParameter = []PlansExpand

// #/paths//v1/plans/get/responses/200/content/application/json/schema
type GetV1Plans200Response struct {
	Data *PlansResponse `json:"data,omitempty" form:"data,omitempty"`
	Meta *Meta          `json:"meta,omitempty" form:"meta,omitempty"`
}

// #/paths//v1/plans/{plan_id}/get/parameters/0/schema
// Fields to expand (use ?expand=features)
type GetV1PlansPlanIDParameter = []PlanExpand

// #/paths//v1/plans/{plan_id}/get/responses/200/content/application/json/schema
type GetV1PlansPlanID200Response struct {
	Data *PlanResponse `json:"data,omitempty" form:"data,omitempty"`
	Meta *Meta         `json:"meta,omitempty" form:"meta,omitempty"`
}

// #/paths//v1/users/{user_id}/get/parameters/0/schema
// Fields to expand (use ?expand=plan&expand=features&expand=subscription)
type GetV1UsersUserIDParameter = []UserExpand

// #/paths//v1/users/{user_id}/get/responses/200/content/application/json/schema
type GetV1UsersUserID200Response struct {
	Data *UserResponse `json:"data,omitempty" form:"data,omitempty"`
	Meta *Meta         `json:"meta,omitempty" form:"meta,omitempty"`
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+xd62/cuBH/7r9ioBZoAqy9Tnq9DwGKwtck16BJa8SXa4E0WHClWS8vEqWQlJ09w/97",
	"QeqxelAS9dhN4uhTEq1IDmeGw9+8lLsTACeMkJGIOs/A+fPZk7NzZ6GeUrYJnWeg3gBwJJU+qjd+5oRJ",
	"sYMXTD8KkEkBF5ev9CAAx0PhchpJGjL1+hvq8lAgv6EuwibkEBBGrim7hitCrmCDRMYcAQuzZTPdIBfp",
	"LE/Ozs/OnROAe01aRORW7Glb3jxZult0P+aPAJxrlIV/qh2QazXmff4EwCluwsl/+LDYjxJxEBC+U0T8",
	"XS2RU0xcF0VGq2nnyet0AwRigRy2RKSDQIZAQETo0g118xnXRKAHIQO5RcpBxOt8Poh8ws7gnUD4G36O",
	"CPP+mo76X3x+/vTH9Jl6q/bgLH1TL0uZ68ceAvE8qiYmPngoCfXFWXErEeEkQIm8yrG7wt8BHEYCrRRq",
	"gyvqFabQP1PNiE8x8l31pwqz3ikOvXquSNSSzDi1CXl1pHC3GJCSbMfOqbRjF+mdCMkpu3ZKP98X/nW/",
	"6OZGyvDh3HiZasTEDOk17cQ8SRRyBEso+p5W4WQmeBSPOgyPh3PxwJQotkgMhIEUAOePHDeKij8s3TCI",
	"QqYs1zKhXSy1yXmRcLoy9L5Juu/raxDOya5GlRJm7PvViT80q4XRoHIUUcgEVvfnPD0/r225SYNTrU1U",
	"mKOIfVmVpxsyiUyaBEqiyKcuUZMufxN6ZgOnGxUisZA8jJBLiqLhDUU8kaTxVytZvk2Z5RinuF+Y1w1w",
	"xLpv1GDzcieWJOzBQnkT5ndTIxOuf0NX1leurnpvZ4acHyzU6SfiwVv8FKM4tvq0iuAF5yFvFv1wjjzp",
	"5Mg7RmK5DTn9HT04hYAKobBayIGyG+JTT0E9+Ii774FfT5928utXxRO9NXhJqI/ed8CXv1icrFdMIlfo",
	"8gr5DXLQpDxM3pwYuOQIdGNO5a4dPl9E9J+4u4jlVr33wXx3nhSfpGtolycDEL29npfZwC6P5zUVEojv",
	"Q75Us7vzMyavkhtCfbL2MfdrPNxQpr2N0vhRQODCtJJ4aBggE9S3DgNq+5iRwIwEZiQwI4EZCUyKBJZ3",
	"6d9W1Ls/HCxQV30etNzBq+cdsCCNMEK4MYY9d0ClAOohk3RDkY8JRO73bw41RURuewXf/DD8CHFUHcPx",
	"U0w5es4zkDzGaSJy5rX6BOIOF3FJZfhAEdYDAVgzvprx1YyvZnw146tp8VXkE9Y/zHKpR1nHWJJF+gRY",
	"ahliAbdUbtP8ccSpqyzKDeGUMCmM6eNSUjh7NioVfJRE36HTd1Mm5bQaPOSknNZghe1zxayq8oOAilqO",
	"3zpQLG9ihokzTJxh4gwTZ5g4HUxc3qk/BgXg7ACjwoFqiRGht2x4Oe5mDRAnKRmccaIBX3w9MNGipC/V",
	"88GBVrXho0RZOxf6siFWTd4Dja+qvT0EzDxD5hkyz5B5hswzZJ4WMscCuVjepf0j/SHzOzXeCjLrHhwh",
	"icQOyCy3CG7MOTKZvK/blpImnjO48G/JTgBHGXMmIMVAZeisHi4yhLgoRWkP14JzWDxda2HItld6WNzq",
	"oZD3eEpGYHSlbt8URm9tzLLA6IUeqsNi9M6FvixGf2eyHg8CoaudfesIvbSHGaHPCH1G6DNCnxH6cISe",
	"d9rv97Rvt083V8TqxcbTEmZHFgdVzG5qj9bBxPqTvEnWDPHNgCDnUKX9sERY473qEN8Pb9HrVL7/bFFu",
	"kWt/wdDgL7dUQEMneEb3Ogx9JMxpPATZ+BothO3+vTGgS4P6ZouZwGXtXu0LiF8aN2hx5ZZV/UM7Cv1F",
	"uWRKlujlOYhHKfAUUPYDHjcxu07HfV0Dv1pGX1bPx2G4rBT5TyL3f3WiqMZp/TTkYNVXb8t+jsRkgatE",
	"vtWvaZdcHbz0vHnoUv2tkMriBvOTuEfhqugh1l0NDzck9uUqMrF9X2XOGl6gTMSbDXUpsnSOVkE0OzZl",
	"HmXeXBeTMkmW84NdSxmvmIJ7995kJY30mQTbasDLyrE34OX709KAo0YBNR61Hy8ern0MnqdZmMFsSdYe",
	"tNeXBlvfssuyyG2L+JtU3loFLbQvW83Y0dFrsTSKYbk5KiKf7EAPOpDWV3VbrzVG2n11uxEQDLilu1o9",
	"BnMpI3IMY8RAzoiJWoebIoR2jD5puftzDiRhwLFcFgPZTNH3XtQsZRuD1Yg6d23PcoBCkGvsNUE/fmj6",
	"jGsO4tBrDEJ29SlG/H13VQQLlvxaU9+n7HpFmLs13UcVtXxOdhBuIAiZ3Gp4k45vMmWUSbxG3sxwlzAX",
	"fb+nJ1PKViiPZo3IYD/XUE/GJdxbrXnVQTTWQ5BdoMCnGgLJkIH3h17UJ0KuNmHcLYLXREhQb4JHr6nU",
	"VVNRgZjBZHAkEr0VkRaRMfoZJA1QSBJEcLtFVhbJLRGQzlclZxPyQC+hdOPHH4YrTixkGNghzeIhgWxg",
	"C+zsXByZJyZhlJqogYq6O6A8NgOIr9FaTsf0RkYlbpWoHcGxkHsDZKVHjVk24tTF3svqUeOWDb3YlQMW",
	"1uOmWNoKlV6m6w1EpRUPiuEt8VeKQn5D/NWnmDCZxP3aqfhXHKyRKzuWjVUGXd4qm57eL2IwP2pkxYx2",
	"H9yfkmVzgkCNgkf63lvADglfAEr37PEobk1jQ5KpDmVnhSQy7sarRewB6ZiBrElGr5INSAtk8I84IOyU",
	"I/HqDWcjSSlMtVJgezXKfqoZxpxtySnxV2MuHz3D8W8ddXpW2qpamCRleykDt/CV3f6siiNvUjSj8Bmk",
	"kx7qqKU9kL11LB03RrOypa1ujV/T9b5ELKMI+8wAo+kibr4lm4TQzCGThWy3YU1uRpsn0OAoLVr8t27r",
	"ZYZHTafV4iq1BAENt1+TC9J0mAc5yW+qNSAtDjFPaiCMh9D22siNyfAp9p8VP1AgorDPBtqN9Azi/2U1",
	"aTVRxDjtSRgdLraOymVhv6w80lMXlc6hGjIsR4jO1W5rc9GeIdk3ykPUfD9S4DyR8QT+SfaFASsEUvwk",
	"QZrGm1TI6RV6lBDsdOmAQvOXbf3EwJqIUjeLpeUwp8b75qtb+54Gy6CcXe3Lc3E8poshXBdTfX1h2GG6",
	"rKWuD3SSoubW104xllO31pehen04itDZBoN0Bt5M+2zMQG4vpkZaTdEJe5c6rc4divSS9+7sCjq2Ukbi",
	"2XJ5nfzvNGf4mQSRj0udjxfLm7yA8nRjKqDsnmFNvFNuLOLtHstCeboJY9Z/1bhQKNt7ME2rI0+xrlgf",
	"DuRU6nkMarAwnL1OV6+gxkMtww31kDdn70KGtequPrdcY46wsxuhi/a35HZI0tHYCtBZ+lLn0qIruK2H",
	"nOZfFChFdTQRbWF0PdgmhK5fbMHDTebAV3IRiVyOo/j5rhY1cQySf6HTqBOb1GtnjVUNpajFMBxTarSY",
	"ujAjdwH3UEbX0aa1bE0Fn/WSw2/TO/zu60+L/oC56HRUbW+fwslqCWyvOsrmM/fVSled66u2gthpJV1K",
	"aTVKvLWb1FbyX1HJrLE6NtPMwZfEEJTwdZUGTVryAY/oZk/T46Pm4vpYmSj7Js2Wikoq0/if/Flnv8lt",
	"T/xXRZrtR/ctuYVoDPw7eHr+oCIenrOHR8SV9AYXELKVThYvICKxQE/9KeTKi3Gx19yFsoLKigyug5gy",
	"pa1PVZg+Ofih6h05qllVkzfZkOZTB2aQ8c0CzZY2d0vEasMRE9n3MLxU5Glo3WEGapZEEoNNroWRylLR",
	"3cmIzkhQlrLsXxs0YVlQnjd1w5jJL1s5dYxagHo2+lgFIiLk3fx9nu5KFxeMLNux1q9ftEFbV7RsnIHt",
	"qVcJCV7Mk3Zuyvb61YcL49NUBv0wH9q2U7RosXB1nehjZktfCsr6nK8UZCn/h3el5ua7xg/7pN8TSD7l",
	"E8utsmlJ47djoIXoSYu/ZN9T+e/pRURPKz8mX1PZIvH2Uio0Up/c/z8AAP//FGrVO2Z9AAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// GetV1Check makes a GET request to /v1/check
	GetV1Check(ctx context.Context, params *GetV1CheckParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetV1Features makes a GET request to /v1/features
	GetV1Features(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetV1FeaturesFeatureId makes a GET request to /v1/features/{feature_id}
	GetV1FeaturesFeatureId(ctx context.Context, featureId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetV1Plans makes a GET request to /v1/plans
	GetV1Plans(ctx context.Context, params *GetV1PlansParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetV1PlansPlanId makes a GET request to /v1/plans/{plan_id}
	GetV1PlansPlanId(ctx context.Context, planId string, params *GetV1PlansPlanIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetV1UsersUserId makes a GET request to /v1/users/{user_id}
	GetV1UsersUserId(ctx context.Context, userId string, params *GetV1UsersUserIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetV1CheckParams defines parameters for GetV1Check.
type GetV1CheckParams struct {
	// user_id (optional)
	UserId *string `form:"user_id" json:"user_id"`
	// feature (optional)
	Feature *string `form:"feature" json:"feature"`
	// expand (optional)
	Expand *[]string `form:"expand" json:"expand"`
}

// GetV1PlansParams defines parameters for GetV1Plans.
type GetV1PlansParams struct {
	// expand (optional)
	Expand *[]string `form:"expand" json:"expand"`
}

// GetV1PlansPlanIdParams defines parameters for GetV1PlansPlanId.
type GetV1PlansPlanIdParams struct {
	// expand (optional)
	Expand *[]string `form:"expand" json:"expand"`
}

// GetV1UsersUserIdParams defines parameters for GetV1UsersUserId.
type GetV1UsersUserIdParams struct {
	// expand (optional)
	Expand *[]string `form:"expand" json:"expand"`
}

// GetV1Check makes a GET request to /v1/check
// Check feature access
func (c *Client) GetV1Check(ctx context.Context, params *GetV1CheckParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1CheckRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetV1Features makes a GET request to /v1/features
// List all features
func (c *Client) GetV1Features(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1FeaturesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetV1FeaturesFeatureId makes a GET request to /v1/features/{feature_id}
// Get feature by ID
func (c *Client) GetV1FeaturesFeatureId(ctx context.Context, featureId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1FeaturesFeatureIdRequest(c.Server, featureId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetV1Plans makes a GET request to /v1/plans
// List all plans
func (c *Client) GetV1Plans(ctx context.Context, params *GetV1PlansParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1PlansRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetV1PlansPlanId makes a GET request to /v1/plans/{plan_id}
// Get plan by ID
func (c *Client) GetV1PlansPlanId(ctx context.Context, planId string, params *GetV1PlansPlanIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1PlansPlanIdRequest(c.Server, planId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetV1UsersUserId makes a GET request to /v1/users/{user_id}
// Get user state
func (c *Client) GetV1UsersUserId(ctx context.Context, userId string, params *GetV1UsersUserIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1UsersUserIdRequest(c.Server, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1CheckRequest creates a GET request for /v1/check
func NewGetV1CheckRequest(server string, params *GetV1CheckParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/check")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()
		if params.UserId != nil {
			if queryFrag, err := StyleFormExplodeParam("user_id", ParamLocationQuery, *params.UserId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Feature != nil {
			if queryFrag, err := StyleFormExplodeParam("feature", ParamLocationQuery, *params.Feature); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Expand != nil {
			if queryFrag, err := StyleFormExplodeParam("expand", ParamLocationQuery, *params.Expand); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1FeaturesRequest creates a GET request for /v1/features
func NewGetV1FeaturesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/features")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1FeaturesFeatureIdRequest creates a GET request for /v1/features/{feature_id}
func NewGetV1FeaturesFeatureIdRequest(server string, featureId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleSimpleParam("feature_id", ParamLocationPath, featureId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/features/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1PlansRequest creates a GET request for /v1/plans
func NewGetV1PlansRequest(server string, params *GetV1PlansParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/plans")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()
		if params.Expand != nil {
			if queryFrag, err := StyleFormExplodeParam("expand", ParamLocationQuery, *params.Expand); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1PlansPlanIdRequest creates a GET request for /v1/plans/{plan_id}
func NewGetV1PlansPlanIdRequest(server string, planId string, params *GetV1PlansPlanIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleSimpleParam("plan_id", ParamLocationPath, planId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/plans/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()
		if params.Expand != nil {
			if queryFrag, err := StyleFormExplodeParam("expand", ParamLocationQuery, *params.Expand); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1UsersUserIdRequest creates a GET request for /v1/users/{user_id}
func NewGetV1UsersUserIdRequest(server string, userId string, params *GetV1UsersUserIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleSimpleParam("user_id", ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()
		if params.Expand != nil {
			if queryFrag, err := StyleFormExplodeParam("expand", ParamLocationQuery, *params.Expand); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

const DateFormat = "2006-01-02"

type Date struct {
	time.Time
}

func (d Date) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Format(DateFormat))
}

func (d *Date) UnmarshalJSON(data []byte) error {
	var dateStr string
	err := json.Unmarshal(data, &dateStr)
	if err != nil {
		return err
	}
	parsed, err := time.Parse(DateFormat, dateStr)
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

func (d Date) String() string {
	return d.Format(DateFormat)
}

func (d *Date) UnmarshalText(data []byte) error {
	parsed, err := time.Parse(DateFormat, string(data))
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

// MarshalText implements encoding.TextMarshaler for Date.
func (d Date) MarshalText() ([]byte, error) {
	return []byte(d.Format(DateFormat)), nil
}

// Format returns the date formatted according to layout.
func (d Date) Format(layout string) string {
	return d.Time.Format(layout)
}

// Nullable is a generic type that can distinguish between:
// - Field not provided (unspecified)
// - Field explicitly set to null
// - Field has a value
//
// This is implemented as a map[bool]T where:
// - Empty map: unspecified
// - map[false]T: explicitly null
// - map[true]T: has a value
type Nullable[T any] map[bool]T

// NewNullableWithValue creates a Nullable with the given value.
func NewNullableWithValue[T any](value T) Nullable[T] {
	return Nullable[T]{true: value}
}

// NewNullNullable creates a Nullable that is explicitly null.
func NewNullNullable[T any]() Nullable[T] {
	return Nullable[T]{false: *new(T)}
}

// Get returns the value if set, or an error if null or unspecified.
func (n Nullable[T]) Get() (T, error) {
	if v, ok := n[true]; ok {
		return v, nil
	}
	var zero T
	if n.IsNull() {
		return zero, ErrNullableIsNull
	}
	return zero, ErrNullableNotSpecified
}

// MustGet returns the value or panics if null or unspecified.
func (n Nullable[T]) MustGet() T {
	v, err := n.Get()
	if err != nil {
		panic(err)
	}
	return v
}

// Set assigns a value.
func (n *Nullable[T]) Set(value T) {
	*n = Nullable[T]{true: value}
}

// SetNull marks the field as explicitly null.
func (n *Nullable[T]) SetNull() {
	*n = Nullable[T]{false: *new(T)}
}

// SetUnspecified clears the field (as if it was never set).
func (n *Nullable[T]) SetUnspecified() {
	*n = nil
}

// IsNull returns true if the field is explicitly null.
func (n Nullable[T]) IsNull() bool {
	if n == nil {
		return false
	}
	_, ok := n[false]
	return ok
}

// IsSpecified returns true if the field was provided (either null or a value).
func (n Nullable[T]) IsSpecified() bool {
	return len(n) > 0
}

// MarshalJSON implements json.Marshaler.
func (n Nullable[T]) MarshalJSON() ([]byte, error) {
	if n.IsNull() {
		return []byte("null"), nil
	}
	if v, ok := n[true]; ok {
		return json.Marshal(v)
	}
	// Unspecified - this shouldn't be called if omitempty is used correctly
	return []byte("null"), nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (n *Nullable[T]) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		n.SetNull()
		return nil
	}
	var v T
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	n.Set(v)
	return nil
}

// ErrNullableIsNull is returned when trying to get a value from a null Nullable.
var ErrNullableIsNull = errors.New("nullable value is null")

// ErrNullableNotSpecified is returned when trying to get a value from an unspecified Nullable.
var ErrNullableNotSpecified = errors.New("nullable value is not specified")

// ParamLocation indicates where a parameter is located in an HTTP request.
type ParamLocation int

const (
	ParamLocationUndefined ParamLocation = iota
	ParamLocationQuery
	ParamLocationPath
	ParamLocationHeader
	ParamLocationCookie
)

// Binder is an interface for types that can bind themselves from a string value.
type Binder interface {
	Bind(value string) error
}

// primitiveToString converts a primitive value to a string representation.
// It handles basic Go types, time.Time, types.Date, and types that implement
// json.Marshaler or fmt.Stringer.
func primitiveToString(value any) (string, error) {
	// Check for known types first (time, date, uuid)
	if res, ok := marshalKnownTypes(value); ok {
		return res, nil
	}

	// Dereference pointers for optional values
	v := reflect.Indirect(reflect.ValueOf(value))
	t := v.Type()
	kind := t.Kind()

	switch kind {
	case reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Int:
		return strconv.FormatInt(v.Int(), 10), nil
	case reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uint:
		return strconv.FormatUint(v.Uint(), 10), nil
	case reflect.Float64:
		return strconv.FormatFloat(v.Float(), 'f', -1, 64), nil
	case reflect.Float32:
		return strconv.FormatFloat(v.Float(), 'f', -1, 32), nil
	case reflect.Bool:
		if v.Bool() {
			return "true", nil
		}
		return "false", nil
	case reflect.String:
		return v.String(), nil
	case reflect.Struct:
		// Check if it's a UUID
		if u, ok := value.(uuid.UUID); ok {
			return u.String(), nil
		}
		// Check if it implements json.Marshaler
		if m, ok := value.(json.Marshaler); ok {
			buf, err := m.MarshalJSON()
			if err != nil {
				return "", fmt.Errorf("failed to marshal to JSON: %w", err)
			}
			e := json.NewDecoder(bytes.NewReader(buf))
			e.UseNumber()
			var i2 any
			if err = e.Decode(&i2); err != nil {
				return "", fmt.Errorf("failed to decode JSON: %w", err)
			}
			return primitiveToString(i2)
		}
		fallthrough
	default:
		if s, ok := value.(fmt.Stringer); ok {
			return s.String(), nil
		}
		return "", fmt.Errorf("unsupported type %s", reflect.TypeOf(value).String())
	}
}

// marshalKnownTypes checks for special types (time.Time, Date, UUID) and marshals them.
func marshalKnownTypes(value any) (string, bool) {
	v := reflect.Indirect(reflect.ValueOf(value))
	t := v.Type()

	if t.ConvertibleTo(reflect.TypeOf(time.Time{})) {
		tt := v.Convert(reflect.TypeOf(time.Time{}))
		timeVal := tt.Interface().(time.Time)
		return timeVal.Format(time.RFC3339Nano), true
	}

	if t.ConvertibleTo(reflect.TypeOf(Date{})) {
		d := v.Convert(reflect.TypeOf(Date{}))
		dateVal := d.Interface().(Date)
		return dateVal.Format(DateFormat), true
	}

	if t.ConvertibleTo(reflect.TypeOf(uuid.UUID{})) {
		u := v.Convert(reflect.TypeOf(uuid.UUID{}))
		uuidVal := u.Interface().(uuid.UUID)
		return uuidVal.String(), true
	}

	return "", false
}

// escapeParameterString escapes a parameter value based on its location.
// Query and path parameters need URL escaping; headers and cookies do not.
func escapeParameterString(value string, paramLocation ParamLocation) string {
	switch paramLocation {
	case ParamLocationQuery:
		return url.QueryEscape(value)
	case ParamLocationPath:
		return url.PathEscape(value)
	default:
		return value
	}
}

// unescapeParameterString unescapes a parameter value based on its location.
func unescapeParameterString(value string, paramLocation ParamLocation) (string, error) {
	switch paramLocation {
	case ParamLocationQuery, ParamLocationUndefined:
		return url.QueryUnescape(value)
	case ParamLocationPath:
		return url.PathUnescape(value)
	default:
		return value, nil
	}
}

// sortedKeys returns the keys of a map in sorted order.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// BindStringToObject binds a string value to a destination object.
// It handles primitives, encoding.TextUnmarshaler, and the Binder interface.
func BindStringToObject(src string, dst any) error {
	// Check for TextUnmarshaler
	if tu, ok := dst.(encoding.TextUnmarshaler); ok {
		return tu.UnmarshalText([]byte(src))
	}

	// Check for Binder interface
	if b, ok := dst.(Binder); ok {
		return b.Bind(src)
	}

	v := reflect.ValueOf(dst)
	if v.Kind() != reflect.Ptr {
		return fmt.Errorf("dst must be a pointer, got %T", dst)
	}
	v = v.Elem()

	switch v.Kind() {
	case reflect.String:
		v.SetString(src)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		i, err := strconv.ParseInt(src, 10, 64)
		if err != nil {
			return fmt.Errorf("failed to parse int: %w", err)
		}
		v.SetInt(i)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		u, err := strconv.ParseUint(src, 10, 64)
		if err != nil {
			return fmt.Errorf("failed to parse uint: %w", err)
		}
		v.SetUint(u)
	case reflect.Float32, reflect.Float64:
		f, err := strconv.ParseFloat(src, 64)
		if err != nil {
			return fmt.Errorf("failed to parse float: %w", err)
		}
		v.SetFloat(f)
	case reflect.Bool:
		b, err := strconv.ParseBool(src)
		if err != nil {
			return fmt.Errorf("failed to parse bool: %w", err)
		}
		v.SetBool(b)
	default:
		// Try JSON unmarshal as a fallback
		return json.Unmarshal([]byte(src), dst)
	}
	return nil
}

// bindSplitPartsToDestinationArray binds a slice of string parts to a destination slice.
func bindSplitPartsToDestinationArray(parts []string, dest any) error {
	v := reflect.Indirect(reflect.ValueOf(dest))
	t := v.Type()

	newArray := reflect.MakeSlice(t, len(parts), len(parts))
	for i, p := range parts {
		err := BindStringToObject(p, newArray.Index(i).Addr().Interface())
		if err != nil {
			return fmt.Errorf("error setting array element: %w", err)
		}
	}
	v.Set(newArray)
	return nil
}

// bindSplitPartsToDestinationStruct binds string parts to a destination struct via JSON.
func bindSplitPartsToDestinationStruct(paramName string, parts []string, explode bool, dest any) error {
	var fields []string
	if explode {
		fields = make([]string, len(parts))
		for i, property := range parts {
			propertyParts := strings.Split(property, "=")
			if len(propertyParts) != 2 {
				return fmt.Errorf("parameter '%s' has invalid exploded format", paramName)
			}
			fields[i] = "\"" + propertyParts[0] + "\":\"" + propertyParts[1] + "\""
		}
	} else {
		if len(parts)%2 != 0 {
			return fmt.Errorf("parameter '%s' has invalid format, property/values need to be pairs", paramName)
		}
		fields = make([]string, len(parts)/2)
		for i := 0; i < len(parts); i += 2 {
			key := parts[i]
			value := parts[i+1]
			fields[i/2] = "\"" + key + "\":\"" + value + "\""
		}
	}
	jsonParam := "{" + strings.Join(fields, ",") + "}"
	return json.Unmarshal([]byte(jsonParam), dest)
}

// BindFormExplodeParam binds a form-style parameter with explode to a destination.
// Form style is the default for query and cookie parameters.
// This handles the exploded case where arrays come as multiple query params.
// Arrays: ?param=a&param=b -> []string{"a", "b"} (values passed as slice)
// Objects: ?key1=value1&key2=value2 -> struct{Key1, Key2} (queryParams passed)
func BindFormExplodeParam(paramName string, required bool, queryParams url.Values, dest any) error {
	dv := reflect.Indirect(reflect.ValueOf(dest))
	v := dv
	var output any

	if required {
		output = dest
	} else {
		// For optional parameters, allocate if nil
		if v.IsNil() {
			t := v.Type()
			newValue := reflect.New(t.Elem())
			output = newValue.Interface()
		} else {
			output = v.Interface()
		}
		v = reflect.Indirect(reflect.ValueOf(output))
	}

	t := v.Type()
	k := t.Kind()

	values, found := queryParams[paramName]

	switch k {
	case reflect.Slice:
		if !found {
			if required {
				return fmt.Errorf("query parameter '%s' is required", paramName)
			}
			return nil
		}
		err := bindSplitPartsToDestinationArray(values, output)
		if err != nil {
			return err
		}
	case reflect.Struct:
		// For exploded objects, fields are spread across query params
		fieldsPresent, err := bindParamsToExplodedObject(paramName, queryParams, output)
		if err != nil {
			return err
		}
		if !fieldsPresent {
			return nil
		}
	default:
		// Primitive
		if len(values) == 0 {
			if required {
				return fmt.Errorf("query parameter '%s' is required", paramName)
			}
			return nil
		}
		if len(values) != 1 {
			return fmt.Errorf("multiple values for single value parameter '%s'", paramName)
		}
		if !found {
			if required {
				return fmt.Errorf("query parameter '%s' is required", paramName)
			}
			return nil
		}
		err := BindStringToObject(values[0], output)
		if err != nil {
			return err
		}
	}

	if !required {
		dv.Set(reflect.ValueOf(output))
	}
	return nil
}

// bindParamsToExplodedObject binds query params to struct fields for exploded objects.
func bindParamsToExplodedObject(paramName string, values url.Values, dest any) (bool, error) {
	binder, v, t := indirectBinder(dest)
	if binder != nil {
		_, found := values[paramName]
		if !found {
			return false, nil
		}
		return true, BindStringToObject(values.Get(paramName), dest)
	}
	if t.Kind() != reflect.Struct {
		return false, fmt.Errorf("unmarshaling query arg '%s' into wrong type", paramName)
	}

	fieldsPresent := false
	for i := 0; i < t.NumField(); i++ {
		fieldT := t.Field(i)
		if !v.Field(i).CanSet() {
			continue
		}

		tag := fieldT.Tag.Get("json")
		fieldName := fieldT.Name
		if tag != "" {
			tagParts := strings.Split(tag, ",")
			if tagParts[0] != "" {
				fieldName = tagParts[0]
			}
		}

		fieldVal, found := values[fieldName]
		if found {
			if len(fieldVal) != 1 {
				return false, fmt.Errorf("field '%s' specified multiple times for param '%s'", fieldName, paramName)
			}
			err := BindStringToObject(fieldVal[0], v.Field(i).Addr().Interface())
			if err != nil {
				return false, fmt.Errorf("could not bind query arg '%s': %w", paramName, err)
			}
			fieldsPresent = true
		}
	}
	return fieldsPresent, nil
}

// indirectBinder checks if dest implements Binder and returns reflect values.
func indirectBinder(dest any) (any, reflect.Value, reflect.Type) {
	v := reflect.ValueOf(dest)
	if v.Type().NumMethod() > 0 && v.CanInterface() {
		if u, ok := v.Interface().(Binder); ok {
			return u, reflect.Value{}, nil
		}
	}
	v = reflect.Indirect(v)
	t := v.Type()
	// Handle special types like time.Time and Date
	if t.ConvertibleTo(reflect.TypeOf(time.Time{})) {
		return dest, reflect.Value{}, nil
	}
	if t.ConvertibleTo(reflect.TypeOf(Date{})) {
		return dest, reflect.Value{}, nil
	}
	return nil, v, t
}

// BindSimpleParam binds a simple-style parameter without explode to a destination.
// Simple style is the default for path and header parameters.
// Arrays: a,b,c -> []string{"a", "b", "c"}
// Objects: key1,value1,key2,value2 -> struct{Key1, Key2}
func BindSimpleParam(paramName string, paramLocation ParamLocation, value string, dest any) error {
	if value == "" {
		return fmt.Errorf("parameter '%s' is empty, can't bind its value", paramName)
	}

	// Unescape based on location
	var err error
	value, err = unescapeParameterString(value, paramLocation)
	if err != nil {
		return fmt.Errorf("error unescaping parameter '%s': %w", paramName, err)
	}

	// Check for TextUnmarshaler
	if tu, ok := dest.(encoding.TextUnmarshaler); ok {
		return tu.UnmarshalText([]byte(value))
	}

	v := reflect.Indirect(reflect.ValueOf(dest))
	t := v.Type()

	switch t.Kind() {
	case reflect.Struct:
		// Split on comma and bind as key,value pairs
		parts := strings.Split(value, ",")
		return bindSplitPartsToDestinationStruct(paramName, parts, false, dest)
	case reflect.Slice:
		parts := strings.Split(value, ",")
		return bindSplitPartsToDestinationArray(parts, dest)
	default:
		return BindStringToObject(value, dest)
	}
}

// StyleFormExplodeParam serializes a value using form style (RFC 6570) with exploding.
// Form style is the default for query and cookie parameters.
// Primitives: paramName=value
// Arrays: paramName=a&paramName=b&paramName=c
// Objects: key1=value1&key2=value2
func StyleFormExplodeParam(paramName string, paramLocation ParamLocation, value any) (string, error) {
	t := reflect.TypeOf(value)
	v := reflect.ValueOf(value)

	// Dereference pointers
	if t.Kind() == reflect.Ptr {
		if v.IsNil() {
			return "", fmt.Errorf("value is a nil pointer")
		}
		v = reflect.Indirect(v)
		t = v.Type()
	}

	// Check for TextMarshaler (but not time.Time or Date)
	if tu, ok := value.(encoding.TextMarshaler); ok {
		innerT := reflect.Indirect(reflect.ValueOf(value)).Type()
		if !innerT.ConvertibleTo(reflect.TypeOf(time.Time{})) && !innerT.ConvertibleTo(reflect.TypeOf(Date{})) {
			b, err := tu.MarshalText()
			if err != nil {
				return "", fmt.Errorf("error marshaling '%s' as text: %w", value, err)
			}
			return fmt.Sprintf("%s=%s", paramName, escapeParameterString(string(b), paramLocation)), nil
		}
	}

	switch t.Kind() {
	case reflect.Slice:
		n := v.Len()
		sliceVal := make([]any, n)
		for i := 0; i < n; i++ {
			sliceVal[i] = v.Index(i).Interface()
		}
		return styleFormExplodeSlice(paramName, paramLocation, sliceVal)
	case reflect.Struct:
		return styleFormExplodeStruct(paramName, paramLocation, value)
	case reflect.Map:
		return styleFormExplodeMap(paramName, paramLocation, value)
	default:
		return styleFormExplodePrimitive(paramName, paramLocation, value)
	}
}

func styleFormExplodePrimitive(paramName string, paramLocation ParamLocation, value any) (string, error) {
	strVal, err := primitiveToString(value)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%s=%s", paramName, escapeParameterString(strVal, paramLocation)), nil
}

func styleFormExplodeSlice(paramName string, paramLocation ParamLocation, values []any) (string, error) {
	// Form with explode: paramName=a&paramName=b&paramName=c
	prefix := fmt.Sprintf("%s=", paramName)
	parts := make([]string, len(values))
	for i, v := range values {
		part, err := primitiveToString(v)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		parts[i] = escapeParameterString(part, paramLocation)
	}
	return prefix + strings.Join(parts, "&"+prefix), nil
}

func styleFormExplodeStruct(paramName string, paramLocation ParamLocation, value any) (string, error) {
	// Check for known types first
	if timeVal, ok := marshalKnownTypes(value); ok {
		return fmt.Sprintf("%s=%s", paramName, escapeParameterString(timeVal, paramLocation)), nil
	}

	// Check for json.Marshaler
	if m, ok := value.(json.Marshaler); ok {
		buf, err := m.MarshalJSON()
		if err != nil {
			return "", fmt.Errorf("failed to marshal to JSON: %w", err)
		}
		var i2 any
		e := json.NewDecoder(bytes.NewReader(buf))
		e.UseNumber()
		if err = e.Decode(&i2); err != nil {
			return "", fmt.Errorf("failed to unmarshal JSON: %w", err)
		}
		return StyleFormExplodeParam(paramName, paramLocation, i2)
	}

	// Build field dictionary
	fieldDict, err := structToFieldDict(value)
	if err != nil {
		return "", err
	}

	// Form style with explode: key1=value1&key2=value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k+"="+v)
	}
	return strings.Join(parts, "&"), nil
}

func styleFormExplodeMap(paramName string, paramLocation ParamLocation, value any) (string, error) {
	dict, ok := value.(map[string]any)
	if !ok {
		return "", errors.New("map not of type map[string]any")
	}

	fieldDict := make(map[string]string)
	for fieldName, val := range dict {
		str, err := primitiveToString(val)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		fieldDict[fieldName] = str
	}

	// Form style with explode: key1=value1&key2=value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k+"="+v)
	}
	return strings.Join(parts, "&"), nil
}

// StyleSimpleParam serializes a value using simple style (RFC 6570) without exploding.
// Simple style is the default for path and header parameters.
// Arrays are comma-separated: a,b,c
// Objects are key,value pairs: key1,value1,key2,value2
func StyleSimpleParam(paramName string, paramLocation ParamLocation, value any) (string, error) {
	t := reflect.TypeOf(value)
	v := reflect.ValueOf(value)

	// Dereference pointers
	if t.Kind() == reflect.Ptr {
		if v.IsNil() {
			return "", fmt.Errorf("value is a nil pointer")
		}
		v = reflect.Indirect(v)
		t = v.Type()
	}

	// Check for TextMarshaler (but not time.Time or Date)
	if tu, ok := value.(encoding.TextMarshaler); ok {
		innerT := reflect.Indirect(reflect.ValueOf(value)).Type()
		if !innerT.ConvertibleTo(reflect.TypeOf(time.Time{})) && !innerT.ConvertibleTo(reflect.TypeOf(Date{})) {
			b, err := tu.MarshalText()
			if err != nil {
				return "", fmt.Errorf("error marshaling '%s' as text: %w", value, err)
			}
			return escapeParameterString(string(b), paramLocation), nil
		}
	}

	switch t.Kind() {
	case reflect.Slice:
		n := v.Len()
		sliceVal := make([]any, n)
		for i := 0; i < n; i++ {
			sliceVal[i] = v.Index(i).Interface()
		}
		return styleSimpleSlice(paramName, paramLocation, sliceVal)
	case reflect.Struct:
		return styleSimpleStruct(paramName, paramLocation, value)
	case reflect.Map:
		return styleSimpleMap(paramName, paramLocation, value)
	default:
		return styleSimplePrimitive(paramLocation, value)
	}
}

func styleSimplePrimitive(paramLocation ParamLocation, value any) (string, error) {
	strVal, err := primitiveToString(value)
	if err != nil {
		return "", err
	}
	return escapeParameterString(strVal, paramLocation), nil
}

func styleSimpleSlice(paramName string, paramLocation ParamLocation, values []any) (string, error) {
	parts := make([]string, len(values))
	for i, v := range values {
		part, err := primitiveToString(v)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		parts[i] = escapeParameterString(part, paramLocation)
	}
	return strings.Join(parts, ","), nil
}

func styleSimpleStruct(paramName string, paramLocation ParamLocation, value any) (string, error) {
	// Check for known types first
	if timeVal, ok := marshalKnownTypes(value); ok {
		return escapeParameterString(timeVal, paramLocation), nil
	}

	// Check for json.Marshaler
	if m, ok := value.(json.Marshaler); ok {
		buf, err := m.MarshalJSON()
		if err != nil {
			return "", fmt.Errorf("failed to marshal to JSON: %w", err)
		}
		var i2 any
		e := json.NewDecoder(bytes.NewReader(buf))
		e.UseNumber()
		if err = e.Decode(&i2); err != nil {
			return "", fmt.Errorf("failed to unmarshal JSON: %w", err)
		}
		return StyleSimpleParam(paramName, paramLocation, i2)
	}

	// Build field dictionary
	fieldDict, err := structToFieldDict(value)
	if err != nil {
		return "", err
	}

	// Simple style without explode: key1,value1,key2,value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k, v)
	}
	return strings.Join(parts, ","), nil
}

func styleSimpleMap(paramName string, paramLocation ParamLocation, value any) (string, error) {
	dict, ok := value.(map[string]any)
	if !ok {
		return "", errors.New("map not of type map[string]any")
	}

	fieldDict := make(map[string]string)
	for fieldName, val := range dict {
		str, err := primitiveToString(val)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		fieldDict[fieldName] = str
	}

	// Simple style without explode: key1,value1,key2,value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k, v)
	}
	return strings.Join(parts, ","), nil
}

// structToFieldDict converts a struct to a map of field names to string values.
func structToFieldDict(value any) (map[string]string, error) {
	v := reflect.ValueOf(value)
	t := reflect.TypeOf(value)
	fieldDict := make(map[string]string)

	for i := 0; i < t.NumField(); i++ {
		fieldT := t.Field(i)
		tag := fieldT.Tag.Get("json")
		fieldName := fieldT.Name
		if tag != "" {
			tagParts := strings.Split(tag, ",")
			if tagParts[0] != "" {
				fieldName = tagParts[0]
			}
		}
		f := v.Field(i)

		// Skip nil optional fields
		if f.Type().Kind() == reflect.Ptr && f.IsNil() {
			continue
		}
		str, err := primitiveToString(f.Interface())
		if err != nil {
			return nil, fmt.Errorf("error formatting field '%s': %w", fieldName, err)
		}
		fieldDict[fieldName] = str
	}
	return fieldDict, nil
}
