// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ProblemDetailsType.
const (
	HTTPSGrantsyExampleErrorsBadRequest       ProblemDetailsType = "https://grantsy.example/errors/bad-request"
	HTTPSGrantsyExampleErrorsInternalError    ProblemDetailsType = "https://grantsy.example/errors/internal-error"
	HTTPSGrantsyExampleErrorsUnauthorized     ProblemDetailsType = "https://grantsy.example/errors/unauthorized"
	HTTPSGrantsyExampleErrorsValidationFailed ProblemDetailsType = "https://grantsy.example/errors/validation-failed"
)

// Defines values for RawSubscriptionProvider.
const (
	Lemonsqueezy RawSubscriptionProvider = "lemonsqueezy"
)

// CheckResult defines model for CheckResult.
type CheckResult struct {
	Allowed bool   `json:"allowed,omitempty"`
	Feature string `json:"feature,omitempty"`
	Plan    string `json:"plan,omitempty"`
	Reason  string `json:"reason,omitempty"`
	UserID  string `json:"user_id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ProblemDetails `json:"error,omitempty"`
}

// FeatureDTO defines model for FeatureDTO.
type FeatureDTO struct {
	// Description Feature description
	Description string `json:"description,omitempty"`

	// ID Feature identifier
	ID string `json:"id,omitempty"`

	// Name Feature display name
	Name string `json:"name,omitempty"`
}

// FeaturesResponse defines model for FeaturesResponse.
type FeaturesResponse struct {
	// Features List of feature IDs available to the user
	Features []string `json:"features"`

	// Plan The user's current plan ID
	Plan string `json:"plan,omitempty"`

	// UserID The user ID
	UserID string `json:"user_id,omitempty"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field,omitempty"`
	Message string `json:"message,omitempty"`
}

// LemonSqueezySubscriptionDTO defines model for LemonSqueezySubscriptionDTO.
type LemonSqueezySubscriptionDTO struct {
	// BillingAnchor Day of month for billing
	BillingAnchor int `json:"billing_anchor,omitempty"`

	// Cancelled Whether the subscription has been cancelled
	Cancelled bool `json:"cancelled,omitempty"`

	// CardBrand Payment card brand
	CardBrand string `json:"card_brand,omitempty"`

	// CardLastFour Last four digits of payment card
	CardLastFour string `json:"card_last_four,omitempty"`

	// CreatedAt Unix timestamp when subscription was created
	CreatedAt int64 `json:"created_at,omitempty"`

	// CustomerID LemonSqueezy customer ID
	CustomerID int `json:"customer_id,omitempty"`

	// EndsAt Unix timestamp when subscription ends
	EndsAt int `json:"ends_at"`

	// ID LemonSqueezy subscription ID
	ID int `json:"id,omitempty"`

	// OrderID LemonSqueezy order ID
	OrderID int `json:"order_id,omitempty"`

	// ProductID LemonSqueezy product ID
	ProductID int `json:"product_id,omitempty"`

	// ProductName Product display name
	ProductName string `json:"product_name,omitempty"`

	// RenewsAt Unix timestamp when subscription renews
	RenewsAt int64 `json:"renews_at,omitempty"`

	// Status Subscription status
	Status string `json:"status,omitempty"`

	// StatusFormatted Human-readable subscription status
	StatusFormatted string `json:"status_formatted,omitempty"`

	// SubscriptionItemID LemonSqueezy subscription item ID
	SubscriptionItemID int `json:"subscription_item_id,omitempty"`

	// TrialEndsAt Unix timestamp when trial ends
	TrialEndsAt int `json:"trial_ends_at"`

	// UpdatedAt Unix timestamp when subscription was last updated
	UpdatedAt int64 `json:"updated_at,omitempty"`

	// VariantID LemonSqueezy variant ID
	VariantID int `json:"variant_id,omitempty"`

	// VariantName Variant display name
	VariantName string `json:"variant_name,omitempty"`
}

// Meta defines model for Meta.
type Meta struct {
	RequestID string `json:"request_id,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
	Version   string `json:"version,omitempty"`
}

// PlanDTO defines model for PlanDTO.
type PlanDTO struct {
	// Features List of feature IDs included in this plan
	Features []string `json:"features"`

	// ID Plan identifier
	ID string `json:"id,omitempty"`

	// Name Plan display name
	Name string `json:"name,omitempty"`

	// Variants Pricing variants for this plan
	Variants []VariantDTO `json:"variants,omitempty"`
}

// PlansResponse defines model for PlansResponse.
type PlansResponse struct {
	// AllFeatures All feature definitions (when expand=features)
	AllFeatures []FeatureDTO `json:"all_features,omitempty"`

	// Plans List of available plans
	Plans []PlanDTO `json:"plans"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail    string             `json:"detail,omitempty"`
	Fields    []FieldError       `json:"fields,omitempty"`
	RequestID string             `json:"request_id,omitempty"`
	Status    int                `json:"status,omitempty"`
	Title     string             `json:"title,omitempty"`
	Type      ProblemDetailsType `json:"type,omitempty"`
}

// ProblemDetailsType defines model for ProblemDetails.Type.
type ProblemDetailsType string

// ProviderSubscription defines model for ProviderSubscription.
type ProviderSubscription struct {
	union json.RawMessage
}

// RawSubscription defines model for RawSubscription.
type RawSubscription struct {
	Data ProviderSubscription `json:"data,omitempty"`

	// Provider Provider identifier
	Provider RawSubscriptionProvider `json:"provider,omitempty"`
}

// RawSubscriptionProvider Provider identifier
type RawSubscriptionProvider string

// SubscriptionResponse defines model for SubscriptionResponse.
type SubscriptionResponse struct {
	// Cancelled Whether the subscription has been cancelled
	Cancelled bool `json:"cancelled,omitempty"`

	// EndsAt Unix timestamp when subscription ends (if cancelled)
	EndsAt int `json:"ends_at"`

	// Features List of feature IDs available to the user
	Features []string `json:"features"`

	// HasSubscription Whether the user has an active subscription
	HasSubscription bool `json:"has_subscription,omitempty"`

	// Plan The user's current plan ID
	Plan string          `json:"plan,omitempty"`
	Raw  RawSubscription `json:"raw,omitempty"`

	// RenewsAt Unix timestamp when subscription renews
	RenewsAt int `json:"renews_at"`

	// Status Subscription status (active, on_trial, paused, past_due, cancelled, expired)
	Status string `json:"status,omitempty"`

	// TrialEndsAt Unix timestamp when trial ends (if on trial)
	TrialEndsAt int `json:"trial_ends_at"`

	// UserID The user ID
	UserID string `json:"user_id,omitempty"`
}

// VariantDTO defines model for VariantDTO.
type VariantDTO struct {
	// HasFreeTrial Whether this variant has a free trial
	HasFreeTrial bool `json:"has_free_trial,omitempty"`

	// ID Variant identifier
	ID int `json:"id,omitempty"`

	// Interval Billing interval (month, year, etc.)
	Interval string `json:"interval,omitempty"`

	// IntervalCount Number of intervals between billings
	IntervalCount int `json:"interval_count,omitempty"`

	// Name Variant display name
	Name string `json:"name,omitempty"`

	// Price Price in cents
	Price interface{} `json:"price,omitempty"`

	// Sort Display order
	Sort int `json:"sort,omitempty"`

	// TrialInterval Trial billing interval
	TrialInterval string `json:"trial_interval,omitempty"`

	// TrialIntervalCount Trial duration in intervals
	TrialIntervalCount int `json:"trial_interval_count,omitempty"`
}

// GetV1CheckParams defines parameters for GetV1Check.
type GetV1CheckParams struct {
	// UserID User ID to check access for
	UserID string `form:"user_id,omitempty" json:"user_id,omitempty"`

	// Feature Feature ID to check access for
	Feature string `form:"feature,omitempty" json:"feature,omitempty"`
}

// GetV1FeaturesParams defines parameters for GetV1Features.
type GetV1FeaturesParams struct {
	// UserID User ID to get features for
	UserID string `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// GetV1PlansParams defines parameters for GetV1Plans.
type GetV1PlansParams struct {
	// Expand Set to 'features' to include feature details
	Expand string `form:"expand,omitempty" json:"expand,omitempty"`
}

// GetV1SubscriptionParams defines parameters for GetV1Subscription.
type GetV1SubscriptionParams struct {
	// UserID User ID to get subscription for
	UserID string `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// AsLemonSqueezySubscriptionDTO returns the union data inside the ProviderSubscription as a LemonSqueezySubscriptionDTO
func (t ProviderSubscription) AsLemonSqueezySubscriptionDTO() (LemonSqueezySubscriptionDTO, error) {
	var body LemonSqueezySubscriptionDTO
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLemonSqueezySubscriptionDTO overwrites any union data inside the ProviderSubscription as the provided LemonSqueezySubscriptionDTO
func (t *ProviderSubscription) FromLemonSqueezySubscriptionDTO(v LemonSqueezySubscriptionDTO) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLemonSqueezySubscriptionDTO performs a merge with any union data inside the ProviderSubscription, using the provided LemonSqueezySubscriptionDTO
func (t *ProviderSubscription) MergeLemonSqueezySubscriptionDTO(v LemonSqueezySubscriptionDTO) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ProviderSubscription) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ProviderSubscription) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV1Check request
	GetV1Check(ctx context.Context, params *GetV1CheckParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Features request
	GetV1Features(ctx context.Context, params *GetV1FeaturesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Plans request
	GetV1Plans(ctx context.Context, params *GetV1PlansParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Subscription request
	GetV1Subscription(ctx context.Context, params *GetV1SubscriptionParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV1Check(ctx context.Context, params *GetV1CheckParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1CheckRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Features(ctx context.Context, params *GetV1FeaturesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1FeaturesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Plans(ctx context.Context, params *GetV1PlansParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1PlansRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Subscription(ctx context.Context, params *GetV1SubscriptionParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1SubscriptionRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1CheckRequest generates requests for GetV1Check
func NewGetV1CheckRequest(server string, params *GetV1CheckParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/check")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserID); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "feature", runtime.ParamLocationQuery, params.Feature); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1FeaturesRequest generates requests for GetV1Features
func NewGetV1FeaturesRequest(server string, params *GetV1FeaturesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/features")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserID); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1PlansRequest generates requests for GetV1Plans
func NewGetV1PlansRequest(server string, params *GetV1PlansParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/plans")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "expand", runtime.ParamLocationQuery, params.Expand); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1SubscriptionRequest generates requests for GetV1Subscription
func NewGetV1SubscriptionRequest(server string, params *GetV1SubscriptionParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/subscription")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_id", runtime.ParamLocationQuery, params.UserID); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV1CheckWithResponse request
	GetV1CheckWithResponse(ctx context.Context, params *GetV1CheckParams, reqEditors ...RequestEditorFn) (*GetV1CheckResponse, error)

	// GetV1FeaturesWithResponse request
	GetV1FeaturesWithResponse(ctx context.Context, params *GetV1FeaturesParams, reqEditors ...RequestEditorFn) (*GetV1FeaturesResponse, error)

	// GetV1PlansWithResponse request
	GetV1PlansWithResponse(ctx context.Context, params *GetV1PlansParams, reqEditors ...RequestEditorFn) (*GetV1PlansResponse, error)

	// GetV1SubscriptionWithResponse request
	GetV1SubscriptionWithResponse(ctx context.Context, params *GetV1SubscriptionParams, reqEditors ...RequestEditorFn) (*GetV1SubscriptionResponse, error)
}

type GetV1CheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data CheckResult `json:"data,omitempty"`
		Meta Meta        `json:"meta,omitempty"`
	}
	JSON400 *ErrorResponse
	JSON401 *ErrorResponse
	JSON422 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetV1CheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1CheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1FeaturesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data FeaturesResponse `json:"data,omitempty"`
		Meta Meta             `json:"meta,omitempty"`
	}
	JSON400 *ErrorResponse
	JSON401 *ErrorResponse
	JSON422 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetV1FeaturesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1FeaturesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1PlansResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data PlansResponse `json:"data,omitempty"`
		Meta Meta          `json:"meta,omitempty"`
	}
	JSON400 *ErrorResponse
	JSON401 *ErrorResponse
	JSON422 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetV1PlansResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1PlansResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1SubscriptionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data SubscriptionResponse `json:"data,omitempty"`
		Meta Meta                 `json:"meta,omitempty"`
	}
	JSON400 *ErrorResponse
	JSON401 *ErrorResponse
	JSON422 *ErrorResponse
	JSON500 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetV1SubscriptionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1SubscriptionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV1CheckWithResponse request returning *GetV1CheckResponse
func (c *ClientWithResponses) GetV1CheckWithResponse(ctx context.Context, params *GetV1CheckParams, reqEditors ...RequestEditorFn) (*GetV1CheckResponse, error) {
	rsp, err := c.GetV1Check(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1CheckResponse(rsp)
}

// GetV1FeaturesWithResponse request returning *GetV1FeaturesResponse
func (c *ClientWithResponses) GetV1FeaturesWithResponse(ctx context.Context, params *GetV1FeaturesParams, reqEditors ...RequestEditorFn) (*GetV1FeaturesResponse, error) {
	rsp, err := c.GetV1Features(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1FeaturesResponse(rsp)
}

// GetV1PlansWithResponse request returning *GetV1PlansResponse
func (c *ClientWithResponses) GetV1PlansWithResponse(ctx context.Context, params *GetV1PlansParams, reqEditors ...RequestEditorFn) (*GetV1PlansResponse, error) {
	rsp, err := c.GetV1Plans(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1PlansResponse(rsp)
}

// GetV1SubscriptionWithResponse request returning *GetV1SubscriptionResponse
func (c *ClientWithResponses) GetV1SubscriptionWithResponse(ctx context.Context, params *GetV1SubscriptionParams, reqEditors ...RequestEditorFn) (*GetV1SubscriptionResponse, error) {
	rsp, err := c.GetV1Subscription(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1SubscriptionResponse(rsp)
}

// ParseGetV1CheckResponse parses an HTTP response from a GetV1CheckWithResponse call
func ParseGetV1CheckResponse(rsp *http.Response) (*GetV1CheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1CheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data CheckResult `json:"data,omitempty"`
			Meta Meta        `json:"meta,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1FeaturesResponse parses an HTTP response from a GetV1FeaturesWithResponse call
func ParseGetV1FeaturesResponse(rsp *http.Response) (*GetV1FeaturesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1FeaturesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data FeaturesResponse `json:"data,omitempty"`
			Meta Meta             `json:"meta,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1PlansResponse parses an HTTP response from a GetV1PlansWithResponse call
func ParseGetV1PlansResponse(rsp *http.Response) (*GetV1PlansResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1PlansResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data PlansResponse `json:"data,omitempty"`
			Meta Meta          `json:"meta,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1SubscriptionResponse parses an HTTP response from a GetV1SubscriptionWithResponse call
func ParseGetV1SubscriptionResponse(rsp *http.Response) (*GetV1SubscriptionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1SubscriptionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data SubscriptionResponse `json:"data,omitempty"`
			Meta Meta                 `json:"meta,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
